# -*- coding: utf-8 -*-
"""Clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lFw-bdSOKZjLikN081GNG29-MHI6HMx

# **1. IMPORT THƯ VIỆN CẦN THIẾT**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# **2. ĐỌC FILE**"""

df = pd.read_excel('Diem_Chuan_8_Truong_DHQG.xlsx')

"""# **3. THỐNG KÊ MÔ TẢ**
- Dữ liệu có 544 dòng và 7 cột, trong đó chỉ có cột Ghi chú có NaN là 422
"""

print(df.describe())
print(df.isnull().sum())
print(df.head(10))
print(df.shape)

"""# **4. XỬ LÝ**

**4.1 Xử lý 5 dòng đầu của Trường Đại Học Khoa Học Sức Khỏe**

- Đảo 5 dòng đầu của hai cột 'Mã ngành' và 'Mã Ngành'
"""

# Đảo 5 dòng đầu tiên (index 0 đến 4)
df.loc[0:4, ['Mã ngành', 'Tên ngành']] = df.loc[0:4, ['Tên ngành', 'Mã ngành']].values
df.head(20)

"""**4.2 Xử lý các phương thức xét tuyển khác Phương Thức xét tuyển điểm đi THPT Quốc Gia**

- Xem các giá trị duy nhất của cột ghi chú

==> 12 giá trị duy nhất, trong đó 'Thang điểm 30', ' nan ', 'Nhóm 1', 'Nhóm 3',  'Nhóm 2' là các phương thức Phương Thức xét tuyển điểm đi THPT Quốc Gia
"""

# Xem các giá trị duy nhất trong cột 'Ghi chú'
values = df['Ghi chú'].unique()

print(values)

"""- **Tiến hành xóa và lưu ra file đã làm sạch**"""

# 1. Làm sạch tên cột (loại bỏ khoảng trắng thừa)
df.columns = df.columns.str.strip()

# 2. Danh sách các giá trị cần giữ lại
target_groups = ['Thang điểm 30', 'Nhóm 1', 'Nhóm 2', 'Nhóm 3']

# 3. Lọc các dòng:
# Giữ lại nếu 'Ghi chú' thuộc danh sách target_groups HOẶC là NaN (ô trống)
df_final = df[df['Ghi chú'].isin(target_groups) | df['Ghi chú'].isna()].copy()

# 4. Xuất ra file CSV mới
df_final.to_csv('Diem_Chuan_THPT_cleaned.csv', index=False, encoding='utf-8-sig')